turtle=input("person 1 put all the friends that you know")
hippos=input("person 2 put all the friends that you know")
hippos=hippos.split()
turtle=turtle.split()
turtle=set(turtle)
hippos=set(hippos)
print(turtle)
print(hippos)
print(turtle.intersection(hippos))
